package Perfect::Hash::Bob;

our $VERSION = '0.01';
use strict;
#use warnings;
our @ISA = qw(Perfect::Hash);

use XSLoader;
XSLoader::load('Perfect::Hash::Bob');

=head1 DESCRIPTION

XS interface to bob jenkins perfect hashes.

=head1 METHDOS

=head2 new $filename, @options

NYI

=head2 perfecthash key

XS method

=head2 false_positives

Returns 1 if the hash might return false positives,
i.e. will return the index of an existing key when
you searched for a non-existing key.

The default is 1, unless you created the hash with the
option C<-no-false-positives>.

=cut

#sub false_positives {
#  return !exists $_[0]->[2]->{'-no-false-positives'};
#}

=head1 LICENSE

The code of the bob jenkins perfect hash is under the public domain.

However, code generated by this library is covered under the same terms
as perl itself, which is dual licensed under the GPL v2 and Artistic 2
licenses.

=cut

1;
