package Perfect::Hash::Bob;

our $VERSION = '0.01';
use strict;
#use warnings;
our @ISA = qw(Perfect::Hash);

use XSLoader;
XSLoader::load('Perfect::Hash::Bob');

=head1 DESCRIPTION

XS interface to bob jenkins perfect hashes.

=head1 METHDOS

=over

=item new $filename, @options

NYI

=item perfecthash key

XS method

=item false_positives

Returns 1 if the hash might return false positives, i.e. will return
the index of an existing key when you searched for a non-existing key.

The default is undef, unless you created the hash with the option
C<-false-positives>.

=item save_c NYI

=back

=head1 LICENSE

The code of the bob jenkins perfect hash is under the public domain.

However, code generated by this library is covered under the same terms
as perl itself, which is dual licensed under the GPL v2 and Artistic 2
licenses.

=cut

1;
