package Perfect::Hash::CMPH;

our $VERSION = '0.01';
use strict;
#use warnings;
our @ISA = qw(Perfect::Hash);

use XSLoader;
XSLoader::load();

=head1 DESCRIPTION

XS interface to the cmph library, the current state of the art library
for perfect hashes and minimal perfect hashes.

=head1 false_positives

Returns 1 if the hash might return false positives,
i.e. will return the index of an existing key when
you searched for a non-existing key.

The default is 1, unless you created the hash with the
option C<-no-false-positives>.

=cut

sub false_positives {
  return !exists $_[0]->[2]->{'-no-false-positives'};
}

=back

=head1 LICENSE

The code of the cmph library is dual licensed under the B<LGPL version 2>
and B<MPL 1.1> licenses. Please refer to the LGPL-2 and MPL-1.1 files in
the F<cmph> subdirectory for the full description of each of the licenses.

For cxxmph, the files F<stringpiece.h> and F<MurmurHash2> are covered by the
BSD and MIT licenses, respectively.

However, code generated by this library is covered under the same terms
as perl itself, which is dual licensed under the GPL v2 and Artistic 2
licenses.

=cut

1;
